# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x08products\">\n\x05Param\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\ncategories\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"}\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07picture\x18\x04 \x01(\t\x12\r\n\x05total\x18\x05 \x01(\x03\x12\x0f\n\x07unit_id\x18\x06 \x01(\x03\x12\x12\n\ncategories\x18\x07 \x01(\t\"3\n\x0cProductsList\x12#\n\x08products\x18\x08 \x03(\x0b\x32\x11.products.Product2M\n\x11ProductController\x12\x38\n\x0bGetProducts\x12\x0f.products.Param\x1a\x16.products.ProductsList\"\x00\x62\x06proto3')



_PARAM = DESCRIPTOR.message_types_by_name['Param']
_PRODUCT = DESCRIPTOR.message_types_by_name['Product']
_PRODUCTSLIST = DESCRIPTOR.message_types_by_name['ProductsList']
Param = _reflection.GeneratedProtocolMessageType('Param', (_message.Message,), {
  'DESCRIPTOR' : _PARAM,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:products.Param)
  })
_sym_db.RegisterMessage(Param)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:products.Product)
  })
_sym_db.RegisterMessage(Product)

ProductsList = _reflection.GeneratedProtocolMessageType('ProductsList', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTSLIST,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:products.ProductsList)
  })
_sym_db.RegisterMessage(ProductsList)

_PRODUCTCONTROLLER = DESCRIPTOR.services_by_name['ProductController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PARAM._serialized_start=27
  _PARAM._serialized_end=89
  _PRODUCT._serialized_start=91
  _PRODUCT._serialized_end=216
  _PRODUCTSLIST._serialized_start=218
  _PRODUCTSLIST._serialized_end=269
  _PRODUCTCONTROLLER._serialized_start=271
  _PRODUCTCONTROLLER._serialized_end=348
# @@protoc_insertion_point(module_scope)
